kwonsuhyuk/OnAndOff

- README.md
- 리드미파일에 공백을 추가
- 깃허브 테스트 해보는중
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
스크린샷이랑 자세한 설명 
>
> ♻️Refactor:리드미 파일 공백 추가(테스트용)

- .prettierrc
> #3 
> prettier 파일 생성 및 코드 방식 설정
> 테스트 파일 생성 후 테스트 확인 (큰따옴표->작은따옴표 변경 / 세미콜론 자동생성)
(코드 저장 전)
(코드 저장 후)
>
> [#3] : prettier 파일 생성

- src/Components/Calendar/MyDatePicker.jsx
- src/Components/MenuBar.jsx
- src/Components/QR/QrScan.jsx
- src/Components/ShowSalary/ShowSalary.jsx
- src/Page/AppGuidePage.jsx
- src/Page/DateCheckPage.jsx
- src/Page/EmployeeListPage.jsx
- src/Page/ManagerSettingPage.jsx
- src/Page/ShowCalendarPage.jsx
- src/Page/signupProcessPage/EmployeeFirstPage.jsx
- src/constant/tourStep.js
> #8 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
steps 배열을 jsx 파일에서 관리하는 것이 아닌 ./constant/tourStep.js 파일에서 관리하는 방식으로 변경
> 
> 상수화 과정에서 빼먹은 것 있으면 말해주세요
> [#8] steps 상수 파일로 따로 분리해서 관리 

- package-lock.json
- package.json
- src/Page/AboutPage.tsx
- src/custom.d.ts
- tsconfig.json
- vite.config.js
- ts 사용위한 패키지 설치 및 설정
- AboutPage 에서 변환 잘 되는지 테스트 완료
> #10 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- ts 적용위한 패키지들 설치 
- ts config파일 설정
- 이미지 불러오는것 위한 custom.d.ts 파일 설정
>
> npm i 하고 실행하여야합니당!! (중요!)
> 앞으로 리팩하는 파일 .tsx 파일 로 변경후에 타입 , 인터페이스 지정 해서 사용하면 됨
> ✨Feat: ts 사용위한 패키지 설치 및 설정

- src/api/index.js
- tailwind.config.js
- tsconfig.json
api/index.js 파일 .val() .exists() 삭제, ref 잘못되어있는 부분 전부 수정
> #17 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- api/index 파일에 .val() , .exists() 함수 잘못 사용한 부분 모두 수정
- ref 잘못 설정되어있는 부분 전부 수정
- await 사용 안되어 있는 부분 모두 수정
- 비동기 함수 사용시에 async/ await 문법 사용시에 promise 객체로 받는 경우 비동기로 받는 부분 await 반드시 써줘야 함!
>
> [#17] :  api/index.js 파일 .val() .exists() 삭제, ref 잘못되어있는 부분 전부 수정

- src/Page/LoginPage.tsx
게스트 로그인 버튼생성
> ex) #이슈번호, #이슈번호
> Guest 로그인 버튼 생성 
>
> 이력서용 자동 로그인 버튼 생성 개발시에도 이 버튼을 사용해서 데이터 넣어주세요 loginpage 건든 거니깐 충돌날것 같으면 pull 후에 작업해주세요
> [#35]: Guest 로그인 버튼 생성 

- package-lock.json
- package.json
- src/App.css
- src/Components/QR/QrScan.tsx
- src/Components/ui/button.tsx
- src/Components/ui/dialog.tsx
- src/Page/AccessCameraPage.jsx
- src/index.css
- src/reset.css
- tailwind.config.js
qr scan 모달 shadcn 적용
> #43
> qr scan 모달 shadcn 적용
> font 부분 일부 수정
>
> [#43] : qr scan 모달 shadcn 적용

- src/Components/auth/EmployeeCompanyForm.tsx
- src/Components/auth/PersonalInfoForm.tsx
- src/Page/signupProcessPage/EmployeeFirstPage.jsx
- src/hooks/useLogin.ts
- src/hooks/useSignup.ts
- src/model/index.ts
> #53 
> 회원가입 이메일,전화번호,비밀번호 기존 p태그 제거 후 placeholder 추가
> useSignup.ts 부분에서 데이터가 store에 저장이 안되는 현상은 해결이 안되서 보류하겠습니다.
>
> [#53] 로그인/회원가입 핫픽스

- src/Components/common/AutoCompleteInput.tsx
- src/Components/common/calendar/MyCalendar.tsx
- src/Components/common/modal/ShowCalendarDetailModal.tsx
- src/Components/company/attendance/PeriodAttCalendarDayCard.tsx
- src/Components/company/attendance/PeriodAttCalendarGrid.tsx
- src/Components/company/attendance/PeriodAttCalendarList.tsx
- src/Components/company/attendance/PeriodAttFilterSection.tsx
- src/Components/ui/switch.tsx
- src/api/commute.api.ts
- src/constants/distance.ts
- src/hooks/employee/useShowCalendar.ts
- src/hooks/manager/usePeriodAttendance.ts
- src/model/types/commute.type.ts
- src/pages/employee/ShowCalendarPage.tsx
- src/util/commute.util.ts
- src/util/date.util.ts
- src/util/mapCommuteDataToCalendar.util.ts
- src/util/vacation.util.ts
> #164 
> 근태 현황 조회 api 함수 생성
- fetchCommutesByPeriod : 특정 직원의 월간 근태 기록 조회 함수
```tsx
export async function fetchCommutesByPeriod(
companyCode: string,
userId: string,
year: string,
month: string,
): Promise<Record<string, TCommuteData> | null> {
const basePath = `attendance/${companyCode}/${year}/${month}`;
try {
const snapshot = await getData<Record<string, Record<string, TCommuteData>>>(basePath);
if (!snapshot) return null;
const result: Record<string, TCommuteData> = {};
Object.entries(snapshot).forEach(([day, users]) => {
const userCommute = users[userId];
if (
userCommute?.startTime ||
userCommute?.endTime ||
userCommute?.startWorkplaceId === "외근" ||
userCommute?.endWorkplaceId === "외근"
) {
result[day] = userCommute;
}
});
return result;
} catch (error) {
console.error("❌ 출퇴근 조회 …
```
> [#164] : 전체/직원 근태 데이터 및 회사 공휴일 데이터 연동

- src/hooks/manager/useVacationRequests.ts
- src/hooks/vacation/useGetEmployeeVacationList.ts
- src/model/types/vacation.type.ts
> #170 
> 휴가 승인 된 데이터가 근태 현황에 업데이트되지 않는 현상 수정
- 테스트 완료
> 관리자가 특정 직원에게 휴가 등록시 직원 휴가페이지에 반영되지 않은 현상 수정
- 테스트 완료
>
> [#170] : 휴가 승인 된 데이터가 근태 현황에 업데이트되지 않는 현상 수정

- package-lock.json
- src/Components/common/modal/WorkPlaceModal.tsx
- src/Components/company/company-settings/workplace-setting/WorkPlaceItem.tsx
- src/Components/company/company-settings/workplace-setting/map/NaverMap.tsx
- src/Components/company/company-settings/workplace-setting/map/WorkPlaceMap.tsx
- src/model/types/company.type.ts
- src/pages/manager/TodayAttenancePage.tsx
> #179 
> 근무지 범위 슬라이더 추가
- 슬라이더(범위)에 따른 지도 범위 변경
- 저장 시 반경 텍스트 표시 (1000m / 2000m는 1km / 2km로 표시됩니다.)
> 페이지 첫 렌더링 (or 페이지 새로고침) 이후 모달을 열었을 때, 원이 안나오는 현상 후...
- 아직 해결책을 찾지 못했네요. 원이 나오긴하지만 아주 작은원으로 렌더링이 되고 있는 상태이고
- 슬라이더를 통해 반경을 변경하면 정상적으로 원이 나오긴합니다. 
> [#179] : 관리자 근무지 범위 설정 기능

- src/App.tsx
- src/Components/common/Loading.tsx
> #185 
> Loading UI 구현
- 간단하게 UI 구현했습니다. 대부분의 로딩상태는 스켈레톤으로 대체할 예정이라 초기 로딩 상태에만 사용할예정입니다.
> [#185]: Loading UI

- src/Components/common/CompanySummaryInfo.tsx
- src/Components/common/PopoverHint.tsx
- src/Components/company/company-settings/EmployeeInviteStep.tsx
- src/Components/employee/EmployeeJobSelection.tsx
- src/Components/employee/EmployeementTypeSelection.tsx
- src/hooks/auth/useSettingEmployee.ts
- src/pages/auth/signupProcessPage/EmployeeFirstPage.tsx
> #187 
- 회사 qa ui 필요없음 지워야함
- 직원 가입시 label icon 수정
- 직원 가입 후에 홈으로 이동하도록 해야함
- 직원 가입시 버튼 색깔 고려해야할듯 → pointcolor 임 현재
- 관리자 회원가입 QR 안내 박스 지움
> [#187] : auth qa

- src/Components/common/chart/CustomLegend.tsx
- src/Components/common/chart/CustomTooltip.tsx
- src/Components/common/modal/VacationChartModal.tsx
- src/Components/company/EmployeeListBox.tsx
- src/Components/company/attendance/DaliyAttendanceUI.tsx
- src/Components/company/vacation/VacationChart.tsx
- src/Components/company/vacation/VacationFilter.tsx
- src/Components/company/vacation/VacationPieChart.tsx
- src/Components/ui/carousel.tsx
- src/constants/chartColor.ts
- src/hooks/vacation/useVacationPieChart.ts
> #194
> 케러셀
- 케러셀 디자인 일부 수정 및 직원 리스트 전체 너비 사용하도록 함 -> 여백 줄임
>  휴가 박스 색상 수정
> 휴가 상세 모달 제목부분 디자인 수정
> 차트 범례, 툴팁 부분 통일
- 직원 리스트 2열로 하는것 대신 1열로 하면서 넓게 사용하도록 구현
- 테이블 밑에 공백줄이기는 후에 다양한 디바이스에서 다시 테스트해보고 수정 필요할 시 수정
> [#194] : chart, 금일 출퇴근 관련 QA

- src/Components/common/modal/CommuteConfirmModal.tsx
- src/Components/common/modal/OutWorkingModal.tsx
- src/Components/employee/mainpageBox/CommuteBoxRenderItem.tsx
- src/Components/employee/mainpageBox/CommuteHistoryBox.tsx
- src/Components/employee/mainpageBox/CommutePageUI.tsx
- src/hooks/employee/useNearbyWorkplaces.ts
- src/pages/employee/CommutePage.tsx
>#190
> 직원 출퇴근 페이지 부분 QA
> 직원 홈 페이지 이번주 출퇴근 현황 연동 안되는 현상 해결
> [#190] : employee commute qa

- src/App.tsx
- src/Components/common/ScrollToTop.tsx
- src/Components/common/modal/SelfCommuteModal.tsx
- src/Components/company/ManagerHomeBoxLayout.tsx
- src/Components/company/TodayCommuteBox.tsx
- src/Components/company/WorkplaceBox.tsx
- src/Components/company/attendance/DaliyAttendanceUI.tsx
- src/Components/ui/DatePicker.tsx
- src/hooks/employee/useCommuteModal.ts
- src/layout/NotLoginLayout.tsx
- src/layout/RootLayout.tsx
> #208
> 수동출퇴근 기능 추가
- 기존 컴포넌트 재활용해서 구현했습니다.
- 외근은 등록할수없고 출,퇴근만 등록할수있습니다. (너무 복잡해짐로직이)
> 로그인 페이지 보였다가 메인페이지로 이동하는 오류수정
- userStore에 isLoading 속성을 사용안했었네요 CurrentUser가 들어온후 isLoading이 true로 온후 로딩하도록 버그수정했습니다.
> 관리자 홈화면 > 아이콘 크기 height, width 7 로 수정
> 리스트 그림자 삭제  -> 기존처럼 스크롤바보이도록함
> [#208] : 수동출퇴근 QA, 로그인 페이지 보이는 버그 수정

- package-lock.json
- src/Components/Seo.tsx
- src/Components/common/modal/EmployeeVacationDetailModal.tsx
- src/Components/common/modal/VacationRequestModal.tsx
- src/Components/employee/vacation/EmployeeVacationTableFilterButton.tsx
- src/Components/employee/vacation/EmployeeVacationYearFilter.tsx
- src/hooks/vacation/useGetEmployeeVacationList.ts
- src/layout/NotLoginLayout.tsx
- src/main.tsx
- src/pages/employee/MyVacationPage.tsx
> #207 
> 휴가 요청 모달 및 휴가 상세 모달 UI 수정
- 모달 크기 조정과 textarea 테두리를 추가했습니다.
- 휴가 유형부분을 저번 관리자 휴가 상세 모달과 같이 수정하였습니다.
> 휴가 상태 필터 정렬
> 기타 오류 사항 개선
- 휴가페이지에서 총 휴가 계산이 탭이랑 연결되어있는 현상
-> 승인된 휴가 기준으로만 통계 집계하게끔 수정하였습니다. <br/>
- 휴가 승인 처리 후, 리스트에서 같은 내용이 추가되는 현상
-> 중복된 내역을 정상화하였습니다.
- 추가적으로 react-helmet -> react-helmet-async 라이브러리 변경 했습니다.
> [#207] : myvacation qa

- package-lock.json
- package.json
- src/Components/common/AppTitle.tsx
- src/Components/common/CompanySummaryInfo.tsx
- src/Components/common/Header.tsx
- src/Components/common/menubar/ManagerMenuBar.tsx
- src/Components/ui/sidebar.tsx
- src/layout/EmployeeLayout.tsx
- src/layout/ManagerLayout.tsx
- src/layout/RootLayout.tsx
- src/pages/employee/EmployeeMenuPage.tsx
> #213
> 인터렉티브 가이드  = react-joyride 선택
- 가장 UI 커스텀 하기 쉽고 다양한 기능 제공
- [JoyRide DOCs](https://docs.react-joyride.com/)
> 구글 폼 메뉴 등록 (직원)
- 임시로 google.com 으로 이동하도록 해놓음 후에 구글폼 구성후에 연결 필요
> 구글 폼 메뉴 등록 (관리자)
- 사이드바 메뉴 하단에 구현
> [#213] : interactive guide setting

- src/Components/common/Header.tsx
- src/Components/common/calendar/MyCalendar.tsx
- src/Components/common/modal/WorkPlaceModal.tsx
- src/Components/company/attendance/PeriodAttFilterSection.tsx
- src/Components/company/company-settings/workplace-setting/map/NaverMap.tsx
- src/Components/company/table/EmployeeModifyModal.tsx
- src/Components/employee/mainpageBox/CommuteBox.tsx
- src/pages/employee/CommutePage.tsx
- src/pages/manager/PeriodAttendancePage.tsx
> #217 
> 쿼리스트링 관련 페이지 seo 최적화
- PeriodAttendancePage.tsx 
```tsx
<Seo
title={
tab === "employee" && selectedEmployee
? `${selectedEmployee.name}님의 근태 현황 | On & Off`
: "기간 출퇴근 | On & Off"
}
description="On & Off에서 근태관리 서비스를 이용해보세요."
/>
```
> 네이버맵 반경 초기 렌더링
- 이제 처음 모달을 열었을 때, 초기 값은 반경 300m로 표시되어 나옵니다.
<br/><br/>
- 직원 페이지에서 출근을 클릭하면 저장된 근무지의 반경 표시가 됩니다.
> 출퇴근기록 달력 현재 날짜 UI 변경
- 기존 검은색 배경에서 테두리로 변경했습니다.
>
> [#217] : guitar qa

- src/Components/company/BasicGuideStepBox.tsx
- src/Components/company/ManagerMainContent.tsx
- src/layout/NotLoginLayout.tsx
> #221 
> 관리자 튜토리얼 박스 제공
- localstorage 속성으로 x 아이콘으로 닫을시 , 혹은 모든 튜토리얼 완료시에 자동으로 안보이도록 구현
> [#221] : 관리자 처음 튜토리얼 박스 제공

- src/Components/company/attendance/PeriodAttCalendarDayCard.tsx
- src/Components/company/attendance/PeriodAttCalendarGrid.tsx
- src/hooks/manager/useVacationRequests.ts
> #268 
> 휴가 요청/등록 페이지 테이블 정렬 (요청순)
> +기간 출퇴근 페이지 범례 배경색 -> 텍스트색 변경
>
> [#268] : created at vacation

- src/Components/auth/AuthTestLoginBtn.tsx
> #285 
> 게스트 로그인 계정 변경
- 관리자 : guestCM -> qamanager
- 직원 : guestEM -> qa1
>
> [#285] : 게스트 로그인 계정 변경
